### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by classicbomb** [seyong92/CRNN-Phoneme-Recognizer#1]
Tried running the file but i got an error about CUDA. Since my pc doesnt have any GPU can i run this program?

C:\Users\jehn\Desktop\CRNN-Phoneme-Recognizer-0.1.0>python infer.py C:/Users/jehn/Desktop/CRNN-Phoneme-Recognizer-0.1.0/configs/models/model-best.pt D:/PythonProjects/audioComparison/Processed_files/test1.1_output.wav D:/PythonProjects/audioComparison/Processed_files/predictions.pth
C:\Users\jehn\AppData\Local\Programs\Python\Python310\lib\site-packages\nnAudio\Spectrogram.py:4: Warning: importing Spectrogram subpackage will be deprecated soon. You should import the feature extractor from the feature subpackage. See actual documentation.
  warnings.warn(
STFT kernels created, time used = 0.0570 seconds
STFT filter created, time used = 0.0020 seconds
Mel filter created, time used = 0.0030 seconds
Traceback (most recent call last):
  File "C:\Users\jehn\Desktop\CRNN-Phoneme-Recognizer-0.1.0\infer.py", line 15, in <module>
    model, config, consts = load_model(args.model_path)
  File "C:\Users\jehn\Desktop\CRNN-Phoneme-Recognizer-0.1.0\phonerec\utils\load_save.py", line 62, in load_model
    model = create_model(config, consts, 'cpu')
  File "C:\Users\jehn\Desktop\CRNN-Phoneme-Recognizer-0.1.0\phonerec\utils\load_save.py", line 35, in create_model
    model = globals()[config.model](config, consts)
  File "C:\Users\jehn\Desktop\CRNN-Phoneme-Recognizer-0.1.0\phonerec\models\crnn.py", line 95, in __init__
    self.feat_ext = FeatureExtractor(config)
  File "C:\Users\jehn\Desktop\CRNN-Phoneme-Recognizer-0.1.0\phonerec\models\feature.py", line 28, in __init__
    center=False).to(config.device)
  File "C:\Users\jehn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1152, in to
    return self._apply(convert)
  File "C:\Users\jehn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
    module._apply(fn)
  File "C:\Users\jehn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 849, in _apply
    self._buffers[key] = fn(buf)
  File "C:\Users\jehn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\jehn\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by seyong92** [comment]
I didn't test with the environment without GPU because it was a personal project.

Could you try adding the line `config.device = 'cpu'` at `load_model` function in  `phonerec/utils/load_save.py` like below?

```python
def load_model(file):
    save_data = torch.load(file, map_location='cpu')
    model_state_dict = save_data['model_state_dict']
    config = AttributeDict(save_data['config'])
    consts = AttributeDict(save_data['consts'])

    config.device = 'cpu'  # here
    model = create_model(config, consts, 'cpu')
    model.load_state_dict(model_state_dict)
    model.to(config.device)

    return model, config, consts
```

**Comment by classicbomb** [comment]
Thank you very much it worked!n
